#!/bin/bash
cd ${OPENSHIFT_REPO_DIR}/php/parser/
MYSQL_CLIENT_FLAGS=MYSQL_CLIENT_COMPRESS
php -e export.php > /dev/null
cd ${OPENSHIFT_REPO_DIR}/php/safe-output/
rm -f export.zip
zip -1 export.zip export.xml
rm -f export.xml
exit
